#
# Sample Batch Queue Script
#
# Option: -q, which batch queue to run in
#PBS -q batch
#
# Option: -l nodes, how many nodes to run on, note
# that the ":ppn=2" directive is important. It
# must always be used.
#PBS -l nodes=32:ppn=2
#
# Option: -l ncpus, how many processors to run on
# is not supported on Turing, request nodes only
##PBS -l ncpus=16
#
#
# Option: -l walltime, request this amount of wall
# clock time for your job.  Format is hh:mm:ss
# The default is 1 hour, the limit is 3 days.
# The following requests 5 hours:
#PBS -l walltime=48:00:00
#
#
# Option: -j oe, combines stdout and stderr into a 
# single file.
#PBS -j oe
#
# Option: -o, specifies the name of the output file
# which will be found in ${PBS_O_WORKDIR} after your
# job completes.
#PBS -o pimc++.out
#
# Option: -N, names the job
#PBS -N pimc++
#
# Change directories to the directory where the qsub 
# command was issued.
cd ${PBS_O_WORKDIR}
#
#
# We now insist users use the rjq command for running 
# all MPI or Charm jobs whether in batch or interactive.
rjq pimc++ Na_16_rho200_T3500_LDA.32kvecs.in 


